### ISSUE TITLE
The toaster prop should pop out a toast when you interact with it.

### ISSUE THREAD

**Issue by marcavis** [frogatto/frogatto#100]
It could be a waffle-toast, too.
https://twitter.com/frogatto/status/394549356935647232

**Comment by rkettering** [comment]
Honestly, I'm thinking of making the toaster be a throwable projectile at some point due to its size, and perhaps when it breaks the toast will be one of the gibs, but I think I'd like to cull this from the bug list for motivational reasons for now, since this is something that's pure fluff for novelty's sake, and I'm staring down a path-to-release death march right now.
