### ISSUE TITLE
Frogatto keeps jumping off of bramble patches

### ISSUE THREAD

**Issue by marcavis** [frogatto/frogatto#112]
When hurt by a bramble patch, Frogatto used to do a little hurt jump, then stay still for a bit while the invincibility kept going; this allowed him to jump off adequately.
Now he's continually doing the small jumps when touching the brambles, even if still invincible, which means there may be places where it's impossible to escape due to it being impossible to find a safe spot from which to jump off.

**Comment by Phanterm** [comment]
The way I see it, could go one of two ways:

A) Leave it in, but tweak the level design around all placement of these brambles (since we have to put in the new objects over the old tiles anyway, it would not be much in the way of extra work) so that players are never damage-locked by brambles. I wonder, too, how possible it would be to change the way brambles deal damage to the player, similar to a projectile. This way, players do not enter damage-stun again while still in the invulnerability period.

B) I wonder how possible it would be to give a little 'bounce' property similar to the springs. Not too much, mind, just enough to offset the time in damage invulnerability/stun.

Personally, I prefer the first option.

**Comment by rkettering** [comment]
When we replace these with objects, this should be solved.

**Comment by rkettering** [comment]
Marking this as closed because #169 already tracks the work that needs to be done
