### ISSUE TITLE
walljumping releases upon pressing an arrow away from the wall

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#161]
That is to say, you cease to cling to the wall the moment you tap a side arrow, and you fall.

This interferes with the current 'muscle-memory' version of walljumping - where you press the arrow away from the wall to indicate that you want to jump away more strongly than otherwise.  It's still possible to trigger the current combo, but if you're off by merely a frame in timing, you just fall instead.

It's also problematic because if you do release from the wall like that, you're no longer able to walljump - you just fall like a rock and can't "course-correct" enough to hit the wall again until you've fallen a long ways.

Not sure yet when this change was introduced.

**Comment by AI0867** [comment]
I think it was originally implemented by me, to give the player a way do detach from a wall faster than just waiting. (When you don't want to jump)

**Comment by Phanterm** [comment]
I love the idea of tapping the down arrow to fall straight down from a wall, but it's hard coded into me to want to hit the directional keys and the jump button to jump off of the wall while having some semblance of control. Otherwise, hitting the jump key and then pressing the movement keys feels very awkward. In my opinion, it would be better to minimize the number of key presses by moving them into one sequence as opposed to two. 

(Additionally, it may be that one day Frogatto might be able to fire some projectiles while clinging to the wall, in which case we might need to have those directional presses free to press. Just an example.)
