### ISSUE TITLE
Death particle effects for flying mushrooms trigger on using a super shot. [gif]

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#179]
![frogpwrglch](https://cloud.githubusercontent.com/assets/3878045/9700516/42ba200a-53cb-11e5-8d97-4bbfd370387a.gif)

**Comment by Phanterm** [comment]
Shouldn't these death particles be nullified by default upon expending an enemy for a super shot? I don't recall this issue with other enemies.

**Comment by rkettering** [comment]
It's accidentally been fixed due to how I've shuffled the death commands around, but I'd like to get this fixed properly - the problem with the current method is you don't get any reward for killing it - the death of the creature is "off the books".  No acquirables, no points, no tracking - and worse, no automatic removal of any attaches.

So I need to make this trigger the real destructor, and work out a way for the death to happen with all the rewards, but none of the effects.  Should be fairly easy to do.

**Comment by rkettering** [comment]
Fixed this the right way in 47c2456.

:squirrel:
