### ISSUE TITLE
Skeeters take no damage/react strangely to energy shot and other abilities.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#180]
They flash when an energy shot is used, and disappear entirely when fire breath is used. 
![damage issue](https://cloud.githubusercontent.com/assets/3878045/9700531/c715f068-53cb-11e5-9be8-4003a9135b11.gif)

**Comment by rkettering** [comment]
I thought this was something easy like lacking a taxonomy, but there's actually some black magic going on here.

Two leads:
- the newly de-synchronized collision mechanics may mean the shots are dying from their "die upon colliding with an opposing thing" behavior before the recipient gets a chance to get hit.
- the fact that energy shots in particular type-change themselves is very very bad - when I removed the aforementioned behavior, it exposed a really nasty bug with the way the energy shots die which causes access to a non-existent object slot (really, trying to access some local properties that don't exist anymore because the object has changed type).

**Comment by rkettering** [comment]
Fixed via:
0891ed61659aa26b93a99b3ebca3b70f404d66a8
8f6f35a60670ce282b8b897f51b2d37c5742cb06
