### ISSUE TITLE
potentially create a mini "HP bar" as an attache object

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#198]
This would only be displayed when a creature actually has HP less than 100%, but this might greatly help make our damage-type system more comprehensible to players;  right now we have a number of damage types which, for certain creatures, deal little enough damage that although you can kill them, you flog away at them for 10+ hits and genuinely wonder "Jesus, how long is this thing going to take to die?  Am I doing any damage at all?"

This feels pretty off even to someone who hand-coded the damage tables and system himself, so it'd probably be much worse to a player who's merely guessing at things.

There are a lot of ways to solve this, but almost all of the more 'aesthetic' ways either involve things (like recoloring or alternate poses) that either our engine would have issues with, or are too much work by a long shot.  HP bars, especially when they're "invisible unless damaged" are an aesthetically neutral way to solve this (not great but definitely not harmful, and they remain useable on any kind of creature), and are scalable by an O(1) function for the number of involved creatures.

**Comment by Phanterm** [comment]
I like the idea, since it takes a little longer to kill enemies in Frogatto than other platformers. One idea is to use numbered damage display. I say this because it becomes relatively easy to discern if players do 'a lot' of damage versus very little, once they get into the flow of things. After a while, players will pretty much memorize enemy health amounts by how much damage it took to destroy them the first time around.

I suggest this because it might be easier and solve our damage comprehension problem while avoiding the issues of visual clutter.

**Comment by DDR0** [comment]
It could be an early item you get, or even start with.

**Comment by rkettering** [comment]
Should now be finished. :+1:
