### ISSUE TITLE
lib.math.clear_line_of_sight_between is painfully slow, may need a C++ implementation

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#226]
Experiencing some serious stuttering/slowdown on rocky-road.cfg - and we don't know why.

Some amount of slowdowns seem to have occurred with the refactor related to hittable_attache;  we could be seeing a case where acorns are accumulating and all getting disposed of in one go, or any number of other possible causes.

We need to compare what's on this level, and what's _not_ on other forest levels, and figure out what the actual culprit is.

**Comment by rkettering** [comment]
It does seem to happen upon moving the camera around (and thus, making other objects active that weren't, before).

**Comment by rkettering** [comment]
The culprit seems to be `lib.math.clear_line_of_sight_between`, used on our rabbits.  dc45d68  disables its use, but we still need to figure out why it's so painfully slow.

It's not strictly necessary for the rabbits, but it's definitely necessary for sniper kitties.

**Comment by Vultraz** [comment]
Would this now be fixed for the Sniper kitties with Dave's recursion fix?

**Comment by DDR0** [comment]
`lib.math.clear_line_of_sight_between` takes into account all the other objects that could be between the two target objects. The sniper kitty actually works on a different algorithm, iirc, which was optimized separately mostly because I forgot about the one in lib.math. As I recall, there was originally a difference in return values that may have been eliminated now which prompted the split. :thinking: We should have a look at recombining those.

@Vultraz It probably impacted them. I think the big-ticket item was collision detection, which I seem to recall I did something to but I don't remember what now.

**Comment by rkettering** [comment]
Seems to be fixed.
