### ISSUE TITLE
Game freeze + crashed when Frogatto falls into funnel of kitten factory

### ISSUE THREAD

**Issue by funkybunky** [frogatto/frogatto#232]
I walked off the treadmill from the right side into the funnel and as Frogatto was about to enter the funnel, the game crashed. I'm on Ubuntu 14.04., error was reported through system tools.

**Comment by DDR0** [comment]
Are you using the stable release, version 1.3.1?

Thank you for reporting. The system tools errors do not make it back to our project.

**Comment by rkettering** [comment]
I've just tested this on the latest version and can't reproduce the issue - there *was* an issue not too long ago in the master branch where the factory funnels were causing an assert like this, so if that was what you were running into, it has since been fixed.

Thanks for the bug report. :+1: Since I can't tell for-or-against, if you're reporting anything, try to only bother reporting stuff on the master branch for now, since we're not maintaining the 1.3.1 stable release anymore.  I appreciate the help.
