### ISSUE TITLE
Assert when key was placed onto thorn objects.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#233]
![image](https://cloud.githubusercontent.com/assets/3878045/11399553/ca77c2b0-934d-11e5-9673-fddaf94c1108.png)

**Comment by rkettering** [comment]
We're currently dealing with this via the `neutral` taxonomy (aka the one that exempts something from any sort of damage types so something just takes 100% from everything), followed by custom annulling of the get_hit_by handler to make it so the object in question can't take any damage from anything.

I'm pondering having some sort of `immortal` taxonomy where it automatically can't take damage from anything, but at the same time I'm worried about having too many "special exceptions that make something invincible" - i.e. if I'm doing this I ought to have everything use the same exception, not have some use one, and others use a different one.  Secondly - we actually might want keys at some point to take damage - we might want to check if they've fallen into acid, and have them dissolve away and respawn where they were first given to the player.


Some other stuff like levers actually do this a bit more deeply by directly overriding the on_collide_object_body function - they don't even have a taxonomy, because they cancel out any-and-all code that might query one.  We want it on the keys, though, because we want a lot of the hittable behavior - like the elastic collision stuff.

We'll call this one finished for the time being.  I'm mostly just typing all this out to help form long-term memories about why I was doing what I did - this ought to be a nice enough solution that we don't need to worry about this anymore.
