### ISSUE TITLE
Falling stalactites have HP bars.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#270]
![image](https://cloud.githubusercontent.com/assets/3878045/13127308/4bc59756-d594-11e5-9a51-48d621d50693.png)

**Comment by rkettering** [comment]
Seems to be fixed in current trunk - I think what "incidentally" fixed it was that all objects at full hp no longer display hp bars, and all falling_harmful objects are one-hitpoint objects that immediately die upon landing - they never have partial hitpoints.  Nevertheless, I should give them an explicit flag...
