### ISSUE TITLE
Game uncompletable on Ubuntu (PARSE ERROR -> Segmentation fault)

### ISSUE THREAD

**Issue by ginjeet** [frogatto/frogatto#285]
Game crashes on map "Dungeon Gateway" after 2 seconds no matter what I try to do.

First I got PARSE ERROR  on ~/frogatto**//**save2.cfg ... save3.cfg ... save4.cfg
Then I decided to copy paste my already existing save.cfg four times and name them as above mentioned, now I get "segmentation faults."

I tried going back to previous maps and going forward, tried playing under different resolutions, etc.

My version is the standard one on Ubuntu (neither -v or --version works, so can't give you more details!)

**Comment by rkettering** [comment]
Could you paste the contents of your save file in this issue?  Unless we get a better lead on this (which your save file might provide), I think I would otherwise have to close this bug for lack of info.

Alternatively, if you can get the **full** error message, that also might help.  "PARSE ERROR" is the start of the message; usually it's followed by what the actual problem is.

:confused: Sorry you're having trouble with this.

**Comment by rkettering** [comment]
Closing this due to insufficient information, and the fact that 1.3 is no longer being maintained given the (eventual) release of our next version.
