### ISSUE TITLE
Clean-up branches

### ISSUE THREAD

**Issue by sweetkristas** [frogatto/frogatto#304]
Can someone please go through all the branches here: https://github.com/frogatto/frogatto/branches/all
And either raise merge requests or delete them as appropriate. It's somewhat of a mess with so many of them currently stale.

**Comment by rkettering** [comment]
Broadly speaking, I think this sounds like a great idea - however, there are definitely one or two that are release branches which we'd like to hold onto as historical documentation.

We're keeping the 1.3_stable and 1.2_stable branches, forever.  Even if we don't use them, I occasionally do compares against them to check what was/wasn't in a given release.

**Comment by sweetkristas** [comment]
Which is fine, I didn't intend that all should be deleted. But things like incorrect-error-location which was last updated a year ago seem to be candidates.

**Comment by rkettering** [comment]
:)  Good, good - I can do some of the legwork on that.

**Comment by rkettering** [comment]
Okay, I've trimmed several really old ones that had no unique commits compared to master (including an `SDL2` one you made).

Ultimately for historical reasons, I'd like to preserve the cube trains branches for now, and anything hagabaka made related to internationalization since I don't know what is/isn't relevant for our next internationalization push.

I'd be nice to pull out the CT stuff into its own repo at some point, but we can always do another cleanup job in the future.
