### ISSUE TITLE
Add solid areas to ethereal blocks to prevent projectiles from flying through them and unintentionally breaking puzzle design.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#355]
As of right now, Frogatto can still shoot through ethereal blocks. This breaks all puzzle design involving this element.

**Comment by rkettering** [comment]
Possibly related to:  https://github.com/frogatto/frogatto/issues/517

**Comment by rkettering** [comment]
From doing a deep audit, it looks like our ethereal puzzles aren't just "not broken by" energy shots going through them, but they're utterly reliant on you doing so — they're impossible to complete without it.

However, we really should be doing the same treatment to ethereal blocks as we did to gates, where we make them solid against thrown objects, because an ant getting caught in one could cause a lot of mayhem.

**Comment by rkettering** [comment]
Hopefully fixing this via:  3b7f84e50
