### ISSUE TITLE
Restore secret areas when saving.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#369]
Currently, when you die, the secret areas are removed. However, when you pass a save point, they are not restored as they should be.

Loosely related to #368, "add support for secret areas that don't get removed".

**Comment by rkettering** [comment]
> So - right now we tackle this feature, IIRC, by actually removing the secret area objects.
The level starts, we immediately scan the whole level and remove all of them, and thus we have no secret areas, because they don't get a chance to mod the level solidity.
However, this means they don't get a chance to come back.
New idea:   instead, they'll just "refrain from applying their solidity mod".   They won't delete themselves.
> 
> This way, we can broadcast to them to "update" when necessary.

**Comment by rkettering** [comment]
Actually from a deep-read on the code, this "suggested way it should work" is actually how it works, right now, and a test on a level has confirmed that it's working as intended.
