### ISSUE TITLE
Helicopter plant won't lose his rotor, after swallowing and spitting the plant

### ISSUE THREAD

**Issue by Cuber01** [frogatto/frogatto#435]
**Problem:** Helicopter plant won't lose his rotor, after swallowing and spitting the plant
**How to reproduce:** Swallow and spit out a helicopter plant

![image](https://user-images.githubusercontent.com/67684800/113272711-397ebe00-92dc-11eb-8600-dcc1e61098c3.png)

**Comment by DDR0** [comment]
lol reproduced
![image](https://user-images.githubusercontent.com/862627/113358839-61314e80-92fb-11eb-8a4a-b59e6b9b8048.png)

**Comment by DDR0** [comment]
OK, this was a weird one. It seems the code to get rid of the rotors had gone missing somewhere in the past, since I know this used to work and I can't find the code now. I've added it into the `shooting_plant`, as that seems to be what receives tongue events due to the `base_type` of the `helicopter_plant`.

Additionally, some setup stuff had changed, and there were cases where two rotors would get added to one plant. This caused me quite some grief, as there were some issues around removal of this specific object which were complicated by neither me nor the code expecting to have to do twice.
