### ISSUE TITLE
Perf issue on conveyance.cfg

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#448]
@rkettering reports an FPS dip on `conveyance.cfg`, probably related to the heavy use of whitewater there.

**Issue Screenshot:**
![perf issues on whitewater level](https://user-images.githubusercontent.com/862627/116148037-4604f500-a695-11eb-86fd-5eb039382a46.png)

**Counter-Example:**
![no perf issues on interior level](https://user-images.githubusercontent.com/862627/116148054-4a311280-a695-11eb-8db9-bd6e81d82467.png)

**Comment by rkettering** [comment]
Upon further digging, this was determined to be a really bizarre issue with gates.
Basically, gates were set to have their default animation be the "open" one, and at frame 1 of level processing, they'd try to "close" themselves.  The open/close animations of the gate change their solidity.  **This triggered a recovery function,** which made the gate (instead of throwing an error), revert to its previous animation, and try setting the animation a second time.   This is meant to be a brief/temporary thing if the player walks under a gate whilst it's trying to close, but this ended up causing an infinite loop.

Fixed in the following commits, one of which should prevent this from occurring on other levels by throwing an error:
281ed48906fc7c75f42ac64ced236067e290deae
56ae0c908caf7e059996310d3d0d33459b6f1338
