### ISSUE TITLE
switch the "victory fanfare" music over to being controlled by the music volume

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#456]
Right now it's much much louder than the surrounding music, and whatever the actual cause of that is, we need to fix it so it's broadly in line with the same volume as all the other music.

**Comment by al0fdf** [comment]
The problem here is that the fanfare sound('musical/FrogattoFanfare.ogg') and the playing of the 'FrogattoDreamAdventure.ogg' music are stacked on top of each other, meaning that simply moving the 'musical/FrogattoFanfare.ogg' to the `music` folder and playing it as music won't work. This would involve getting the current music volume, and using it to play the sound effect.
