### ISSUE TITLE
Ant in a bad position on (unknown) level:

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#534]
`downhill.cfg`, second save point.   Ominously this may be a save-related issue.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/863312/157593732-0978485b-9cc4-450c-bec4-c540673a860f.png">

**Comment by DDR0** [comment]
Cause of issue:
![image](https://user-images.githubusercontent.com/862627/176058513-da2cd93e-31e7-40a1-ad8a-5d4a912468b5.png)
The black ant that walks into the secret area at the top of the level causes this assert because the level controller which sets solidity hasn't been run yet, so the area is solid when loaded and the assert triggers.

**Comment by DDR0** [comment]
An appropriate fix for this might be to add a new engine event which fires before object/level solidity is checked, and have secret passage controllers use that.
