### ISSUE TITLE
Characters do not turn towards you when you talk to them.

### ISSUE THREAD

**Issue by Vultraz** [frogatto/frogatto#538]
Small QOL issue. It seems to be something with `turn_towards_player` in `standing_npc.cfg`. From testing, I *think* removing the `should_turn` fixes the issue, but I'm not 100% sure.

**Comment by rkettering** [comment]
Seems to be limited to the `walking_npc` - the `standing_npc` variants behave correctly (including keeping their back to you if they're set to not automatically turn — I feel like that's desirable behavior).

The `walking_npc` heroes seem to be the ones misbehaving — they've got both a lack of turning to the player where the player tries to talk to them, but also they just aren't respecting the `standing_npc` turn behavior, which they really ought to revert to if they're not (currently) walking around.

**Comment by rkettering** [comment]
Fixed by a large rework:
31bb1ed9c9435179cec576a394e923b9cb47a6e7
42cd37260af2c8a5c345a3ceaf3961454798683b
f0d58feb2d98011b352625f7c7a32b5c3a20bab8
11686b48696654fadfbf4ffd53bd9b1b893ba6b5
10b291a7e80d0235d2da31d7df954e6b6e2e614f
c3d8d8e28e5756058b11c8f40954d0ab0291d446
d1df86abfe0d5266703f9a05a43bc47948534977
5291bdcdc4f8e2ab6880a5dfe94f8de10c2b3a6a
8b0351854518af25b553c7fd50f6f2afb6d5e71b
b6a44b135d49d1a7e42fd644c6525d7dd9010016
e2cc12d35c2945b990a111b07f3ef3e68909a9a5
8b42a3768381648178be4d3e837367c665f3c4b4
bcb8dd76bee5ce60b5076f678a4898fdfd8431e5
1c5ff1ec2b33d124386e7cc57521d28444ea3113
bde28c7ef976fdaa9b2ddf62f7e6e37a31a6976e
