### ISSUE TITLE
UI Skull icon not stuck to right of screen

### ISSUE THREAD

**Issue by Vultraz** [frogatto/frogatto#539]
Reported on Discord and confirmed:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/3558659/157995055-ffde7e14-83b8-4101-8093-69e1ef5ef865.png">

**Comment by rkettering** [comment]
Since I'm guessing both of you are running without any options, and therefore, the game starts in widescreen whilst in windowed mode, and transitions to, again, widescreen in fullscreen mode, this may be sort of an engine issue in terms of how the screen size is reported.

Unlike our "upper-left" components, which simply have a nice, clean, flat value that has **no** dependency on the screen size, the "upper-right" components all have an expression for their position that's something like `screen_width - 50`.

Likely this same issue is happening with the gold indicator.

**Comment by rkettering** [comment]
There's an event name:  `window_resize` fired on player object which may help with this.

**Comment by rkettering** [comment]
We've fixed this in ed3e0dd17

**Comment by rkettering** [comment]
Also fixed in anura commit:  https://github.com/anura-engine/anura/commit/849dce25c925c38ea81291f394f97843c2d06a11
